In [416]:
import pandas as pd #data analysis and converting the data into dataframe
import numpy as np #numpy for array processing
import matplotlib.pyplot as plt #2D graph plotting
from sklearn.metrics import r2_score
data=pd.read_csv('data.csv') #reading the dataset
data.head() #displaying the dataset into tabular format

Age  Weight         SBP
0   58      58  158.657118
1   65      90  159.342444
2   56      96  153.516056
3   61      72  155.236048
4   65      62  149.324298

In [417]:
data.tail()

Age  Weight         SBP
89   63      90  158.104033
90   36      94  126.836732
91   60      90  151.953700
92   65      96  149.697360
93   65      96  158.461571

In [418]:
data.shape

(94, 3)

In [419]:
data.isnull().sum()

Age       0
Weight    0
SBP       0
dtype: int64

In [420]:
data.duplicated().sum()

0

In [421]:
data.describe()

Age     Weight         SBP
count  94.000000  94.000000   94.000000
mean   58.925532  82.989362  148.794614
std     7.682181  13.376673    8.947818
min    36.000000  54.000000  124.881162
25%    53.000000  72.000000  142.256824
50%    60.000000  85.000000  150.104128
75%    64.750000  96.000000  154.355503
max    85.000000  99.000000  167.854930

In [422]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 94 entries, 0 to 93
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Age     94 non-null     int64  
 1   Weight  94 non-null     int64  
 2   SBP     94 non-null     float64
dtypes: float64(1), int64(2)
memory usage: 2.3 KB


In [423]:
data.cov()

Age      Weight        SBP
Age     59.015900    4.042210  52.624829
Weight   4.042210  178.935369  -2.830123
SBP     52.624829   -2.830123  80.063444

In [424]:
data.corr()

Age    Weight       SBP
Age     1.000000  0.039336  0.765577
Weight  0.039336  1.000000 -0.023645
SBP     0.765577 -0.023645  1.000000

In [425]:
x=data.iloc[:,0:2] #features/columns
x.head()

Age  Weight
0   58      58
1   65      90
2   56      96
3   61      72
4   65      62

In [426]:
y=data.iloc[:,-1] #target or labels
y

0     158.657118
1     159.342444
2     153.516056
3     155.236048
4     149.324298
         ...    
89    158.104033
90    126.836732
91    151.953700
92    149.697360
93    158.461571
Name: SBP, Length: 94, dtype: float64

In [427]:
from sklearn import preprocessing
minmax=preprocessing.MinMaxScaler(feature_range=(0,1))
minmax.fit(x).transform(x)

array([[0.44897959, 0.08888889],
       [0.59183673, 0.8       ],
       [0.40816327, 0.93333333],
       [0.51020408, 0.4       ],
       [0.59183673, 0.17777778],
       [0.24489796, 0.55555556],
       [0.34693878, 0.33333333],
       [0.36734694, 0.93333333],
       [0.63265306, 0.93333333],
       [0.51020408, 0.        ],
       [0.20408163, 0.28888889],
       [0.34693878, 1.        ],
       [0.55102041, 0.44444444],
       [0.55102041, 0.42222222],
       [0.34693878, 0.68888889],
       [0.71428571, 0.57777778],
       [0.48979592, 0.93333333],
       [0.44897959, 0.62222222],
       [0.34693878, 0.93333333],
       [0.65306122, 0.4       ],
       [0.40816327, 0.8       ],
       [0.40816327, 0.93333333],
       [0.26530612, 0.4       ],
       [0.12244898, 0.53333333],
       [0.46938776, 0.93333333],
       [0.26530612, 0.93333333],
       [0.53061224, 0.        ],
       [0.65306122, 0.28888889],
       [0.3877551 , 1.        ],
       [0.3877551 , 0.44444444],
       [0.

In [428]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=42)

In [429]:
from sklearn.tree import DecisionTreeRegressor  #packages for decision tree
dtc_clf=DecisionTreeRegressor() #model creation
dtc_clf.fit(x_train,y_train) #model training

DecisionTreeRegressor()

In [430]:
y_pred=dtc_clf.predict(x_test)
y_pred

array([162.5753678, 146.3242998, 138.8888882, 133.3837178, 148.5578745,
       162.5753678, 152.5929905, 151.0721922, 146.3242998, 165.9990044])

In [431]:
r2_score(y_test, y_pred)

0.444882857146634

In [432]:
pd.DataFrame({'actual':y_test,'prediction':y_pred})

actual  prediction
40  158.487778  162.575368
22  137.819893  146.324300
55  135.412569  138.888888
72  141.424900  133.383718
0   158.657118  148.557874
26  154.967396  162.575368
39  138.233330  152.592991
67  147.536705  151.072192
10  134.018876  146.324300
44  167.854930  165.999004

In [433]:
from sklearn.ensemble import RandomForestRegressor
clf=RandomForestRegressor(n_estimators=50)
clf.fit(x_train,y_train)

RandomForestRegressor(n_estimators=50)

In [434]:
y_pred2=clf.predict(x_test)
y_pred2

array([155.01319944, 141.01591149, 138.6063095 , 135.65281579,
       148.92679462, 155.84450621, 147.1911387 , 152.62150169,
       142.27545637, 159.4972293 ])

In [435]:
pd.DataFrame({'actual':y_test,'prediction':y_pred2})

actual  prediction
40  158.487778  155.013199
22  137.819893  141.015911
55  135.412569  138.606309
72  141.424900  135.652816
0   158.657118  148.926795
26  154.967396  155.844506
39  138.233330  147.191139
67  147.536705  152.621502
10  134.018876  142.275456
44  167.854930  159.497229

In [436]:
r2_score(y_test, y_pred2)

0.6781720932708397

In [437]:
from sklearn.linear_model import LinearRegression
LR = LinearRegression()
LR.fit(x_train, y_train)
pred_linreg_all = LR.predict(x_test)
pred_linreg_all

array([153.48201404, 140.46707834, 142.93851578, 141.15869627,
       148.30699263, 151.76990393, 145.4873354 , 154.1639592 ,
       137.94727704, 164.61072974])

In [438]:
pd.DataFrame({'actual':y_test,'prediction':pred_linreg_all})

actual  prediction
40  158.487778  153.482014
22  137.819893  140.467078
55  135.412569  142.938516
72  141.424900  141.158696
0   158.657118  148.306993
26  154.967396  151.769904
39  138.233330  145.487335
67  147.536705  154.163959
10  134.018876  137.947277
44  167.854930  164.610730

In [439]:
r2_score(y_test, pred_linreg_all)

0.7391037521751046

In [441]:
import pickle
model_pkl_file = "bp.pkl"  
with open(model_pkl_file, 'wb') as file:  
    pickle.dump(LR, file)